-- GOAI 1.0.0: 受控部署动作和幂等事实。
CREATE TABLE IF NOT EXISTS `xnet_mlops_mep_deployment_action` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `uid` VARCHAR(64) NOT NULL,
    `deployment_uid` VARCHAR(64) NOT NULL,
    `action_type` VARCHAR(32) NOT NULL,
    `from_revision` BIGINT NULL,
    `target_revision` BIGINT NOT NULL,
    `status` VARCHAR(16) NOT NULL,
    `stage` VARCHAR(32) NOT NULL,
    `request_id` VARCHAR(128) NOT NULL,
    `workspace_id` VARCHAR(64) NOT NULL,
    `incident_id` VARCHAR(64) NOT NULL,
    `trace_id` VARCHAR(64) NOT NULL,
    `approval_id` VARCHAR(64) NOT NULL,
    `idempotency_key` VARCHAR(128) NOT NULL,
    `request_digest` CHAR(64) NOT NULL,
    `expected_resource_version` VARCHAR(64) NOT NULL,
    `verification_policy_json` JSON NOT NULL,
    `dry_run` BOOLEAN NOT NULL DEFAULT FALSE,
    `error_code` VARCHAR(64) NULL,
    `error_message` VARCHAR(500) NULL,
    `started_at` DATETIME(3) NULL,
    `completed_at` DATETIME(3) NULL,
    `created_by` VARCHAR(128) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_mep_action_uid` (`uid`),
    UNIQUE KEY `uk_mep_action_idempotency` (`workspace_id`, `action_type`, `idempotency_key`),
    KEY `idx_mep_action_trace` (`workspace_id`, `incident_id`, `trace_id`),
    KEY `idx_mep_action_status` (`status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='GOAI 部署动作';
