

spring.application.name=mlops-login
# ????
server.port=8181

# JDBC URL
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/XnetMLops?useSSL=false&serverTimezone=UTC

# ??????
spring.datasource.username=root

# ?????
spring.datasource.password=${DB_PASSWORD:}

# ???????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# application.properties
spring.data.redis.host=${REDIS_HOST:localhost}

spring.data.redis.port=${REDIS_PORT:6379}

# ?? 256 ?
jwt.secret=${JWT_SECRET}
# 24?????????
jwt.expiration=86400000

# SMS
Spug.url=https://push.spug.cc/send/v3aDVjBzxWjJeX9M
Apps.Name = XnetMLops

logging.level.root=debug
